package engine.moves.dragon;

import engine.moves.Move;

public class DragonPulse extends DragonMove {

	/**
	 * id 411
	 * special move
	 * base power 120
	 * base accuracy 80
	 * pp 5
	 */
	public DragonPulse() {
		super(406, Move.SPECIAL, 85, 1, 10, "Dragon Pulse");
		setDescription("The target is attacked with a shock wave generated by the user's gaping mouth.");
		setPulse(true);
	}

	@Override
	public Move newInstance() {
		return new DragonPulse();
	}

}
